ci: 🛠️ Add validation for coverage report existence and improve SonarQube analysis steps

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -72,17 +72,41 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
+          echo "=== Validando directorios y existencia del archivo de cobertura ==="
+          
+          echo "Directorio actual:"
+          pwd
+          
+          echo "Archivos en el directorio actual:"
+          ls -la
+          
+          echo "Archivos en el directorio de pruebas:"
+          ls -la tests/JobMagnet.Unit.Tests
+          
+          echo "Verificando la existencia de coverage.cobertura.xml..."
+          if [ -f "tests/JobMagnet.Unit.Tests/coverage.cobertura.xml" ]; then
+            echo "Archivo de cobertura encontrado:"
+            realpath tests/JobMagnet.Unit.Tests/coverage.cobertura.xml
+          else
+            echo "Error: El archivo de cobertura no existe en la ruta especificada."
+            exit 1
+          fi
+          
+          echo "=== Iniciando análisis de SonarQube ==="
           dotnet sonarscanner begin \
             /k:"henksandoval_JobMagnetic-BackEnd" \
             /o:"henksandoval" \
             /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
-            /d:sonar.cs.cobertura.reportPaths=tests/JobMagnet.Unit.Tests/coverage.cobertura.xml \
+            /d:sonar.cs.cobertura.reportPaths=$(realpath tests/JobMagnet.Unit.Tests/coverage.cobertura.xml) \
             /d:sonar.language=cs \
             /d:sonar.dotnet.excludeTestProjects=true \
             /d:sonar.sources=sources/JobMagnet \
             /d:sonar.tests=tests/JobMagnet.Unit.Tests \
             /d:sonar.sourceEncoding=UTF-8 \
             /d:sonar.verbose=true
-          
+
+          echo "=== Compilando proyecto ==="
           dotnet build --no-incremental
+          
+          echo "=== Finalizando análisis de SonarQube ==="
           dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
